src/Entity/Monvoyage.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\MonvoyageRepository")
 */
class Monvoyage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Madestination", cascade={"persist", "remove"})
     */
    private $destination;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_depart;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_arrive;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Utilisateur", cascade={"persist", "remove"})
     */
    private $utilisateur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDestination(): ?Madestination
    {
        return $this->destination;
    }

    public function setDestination(?Madestination $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getDateArrive(): ?\DateTimeInterface
    {
        return $this->date_arrive;
    }

    public function setDateArrive(\DateTimeInterface $date_arrive): self
    {
        $this->date_arrive = $date_arrive;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

}

src/Form/MonvoyageType.php
<?php

namespace App\Form;

use App\Entity\Monvoyage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Madestination;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class MonvoyageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_depart', DateType::class,[
                'widget' => 'single_text'
            ])
            ->add('date_arrive', DateType::class,[
                'widget' => 'single_text'
            ])
            ->add('destination',EntityType::class,[
                    'class'         => Madestination::class,
                    'choice_label'  => 'nom_pays'
                ])
            //->add('utilisateur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Monvoyage::class,
        ]);
    }
}

src/Controller/MonvoyageController.php
<?php

namespace App\Controller;

use App\Entity\Monvoyage;
use App\Form\MonvoyageType;
use App\Repository\MonvoyageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/voyage")
 */
class MonvoyageController extends AbstractController
{
    /**
     * @Route("/", name="monvoyage_index", methods={"GET"})
     */
    public function index(MonvoyageRepository $monvoyageRepository): Response
    {

        return $this->render('monvoyage/index.html.twig', [
            'monvoyages' => $monvoyageRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="monvoyage_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $monvoyage = new Monvoyage();
        $form = $this->createForm(MonvoyageType::class, $monvoyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($monvoyage);
            $entityManager->flush();

            return $this->redirectToRoute('monvoyage_index');
        }

        return $this->render('monvoyage/new.html.twig', [
            'monvoyage' => $monvoyage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="monvoyage_show", methods={"GET"})
     */
    public function show(Monvoyage $monvoyage): Response
    {
        return $this->render('monvoyage/show.html.twig', [
            'monvoyage' => $monvoyage,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="monvoyage_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Monvoyage $monvoyage): Response
    {
        $form = $this->createForm(MonvoyageType::class, $monvoyage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('monvoyage_index', [
                'id' => $monvoyage->getId(),
            ]);
        }

        return $this->render('monvoyage/edit.html.twig', [
            'monvoyage' => $monvoyage,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="monvoyage_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Monvoyage $monvoyage): Response
    {
        if ($this->isCsrfTokenValid('delete'.$monvoyage->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($monvoyage);
            $entityManager->flush();
        }

        return $this->redirectToRoute('monvoyage_index');
    }
}

templates/monvoyage/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/monvoyage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Voyage{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                   <h1 style="text-align:center">Editer Voyage</h1>
                </header>
                <div class="panel-body">
                <div class="form">
                <form>
                    <div class="form-group ">
                      <div class="col-lg-9 col-md-offset-2">
                        {{ include('utilisateur/_form.html.twig', {'button_label': 'Update'}) }}
                      </div>
                    </div>
                    
                </form>
                </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

templates/monvoyage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur index{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <h1 style="text-align:center">Listes des voyages</h1>
                </header>

                <table class="table table-striped table-advance table-hover" id="user">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <th>Destination</th>
                            <th>Date_depart</th>
                            <th>Date_arrive</th>
                            <th>utilisateur</th>
                            <th>actions</th>
                        </tr>
                         {% for monvoyage in monvoyages %}
                        <tr>
                            <td>{{ monvoyage.id }}</td>
                            <td>{{ monvoyage.destination.getNomPays() }}</td>
                            <td>{{ monvoyage.dateDepart ? monvoyage.dateDepart|date('Y-m-d H:i:s') : '' }}</td>
                            <td>{{ monvoyage.dateArrive ? monvoyage.dateArrive|date('Y-m-d H:i:s') : '' }}</td>
                            <td>{{ monvoyage.utilisateur }}</td>
                            <td>
                              <div class="btn-group">
                                <a href="#" class="btn btn-danger delete-monvoyage" data-id={{monvoyage.id}}>Supprimer</a>
                                <a href="{{ path('monvoyage_edit', {'id': monvoyage.id}) }}" class="btn btn-warning">Modifier</a>
                              </div>
                            </td>
                        </tr>
                        {% else %}
                            <tr>
                                <td colspan="7">no records found</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </section>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{asset('js/main.js')}}"></script>  
    
{% endblock %}

templates/monvoyage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Monvoyage{% endblock %}

{% block body %}
    <div class="row">
         <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                   <h1 style="text-align:center">Ajouter Voyage</h1>
                </header>
                <div class="panel-body">
                <div class="form">
                <form method="post">
                    <div class="form-group ">
                      <div class="col-lg-9 col-md-offset-2">
                        {{ include('utilisateur/_form.html.twig') }}
                      </div>
                    </div>
                    
                </form>
                </div>
                </div>
            </section>
        </div>
    </div>
{% endblock %}